import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import Header from '@/components/layouts/Header/Header'
import NextAuthProvider from '@/lib/next-auth/NextAuthProvider'
import { ThemeProvider } from '@/components/elements/Provider/ThemeProvider'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body
        className={cn('min-h-screen bg-background font-sans antialiased', notoSansJP.className)}
      >
        <NextAuthProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='Light'
            enableSystem
            disableTransitionOnChange
          >
            <div className='xl:w-2/3 w-full mx-auto '>
              <Header />
              <div className='flex flex-col items-center justify-between'>{children}</div>
            </div>
            <Toaster />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
