import { Noto_Sans_JP } from 'next/font/google'
import React from 'react'
import './globals.css'

import MainLayout from '@/components/layouts/Layout/MainLayout'

import NextAuthProvider from '@/lib/next-auth/NextAuthProvider'
import { cn } from '@/lib/utils'

import type { Metadata } from 'next'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body
        className={cn('min-h-screen bg-background font-sans antialiased', notoSansJP.className)}
      >
        <NextAuthProvider>
          <MainLayout>{children}</MainLayout>
        </NextAuthProvider>
      </body>
    </html>
  )
}
